const CATEGORIES = [
    { id: 'amizade', name: 'Amizade' },
    { id: 'amor_romance', name: 'Amor e Romance' },
    { id: 'carros_motos', name: 'Carros e Motos' },
    { id: 'cidades', name: 'Cidades' },
    { id: 'compra_venda', name: 'Compra e Venda', requires_fee: true },
    { id: 'concursos', name: 'Concursos', requires_fee: true },
    { id: 'desenhos_animes', name: 'Desenhos e Animes' },
    { id: 'divulgacao', name: 'Divulgação', requires_fee: true },
    { id: 'educacao', name: 'Educação' },
    { id: 'emagrecimento', name: 'Emagrecimento', requires_fee: true },
    { id: 'esportes', name: 'Esportes', requires_fee: true },
    { id: 'eventos', name: 'Eventos', requires_fee: true },
    { id: 'fas', name: 'Fãs', requires_fee: true },
    { id: 'figurinhas_stickers', name: 'Figurinhas e Stickers' },
    { id: 'filmes_series', name: 'Filmes e Séries', requires_fee: true },
    { id: 'frases_mensagens', name: 'Frases e Mensagens' },
    { id: 'futebol', name: 'Futebol', requires_fee: true },
    { id: 'games_jogos', name: 'Games e Jogos', requires_fee: true },
    { id: 'ganhar_dinheiro', name: 'Ganhar Dinheiro', requires_fee: true },
    { id: 'imobiliaria', name: 'Imobiliária', requires_fee: true },
    { id: 'investimentos_financas', name: 'Investimentos e Finanças', requires_fee: true },
    { id: 'links', name: 'Links' },
    { id: 'memes_engracados', name: 'Memes Engraçados' },
    { id: 'moda_beleza', name: 'Moda e Beleza', requires_fee: true },
    { id: 'musica', name: 'Música' },
    { id: 'namoro', name: 'Namoro' },
    { id: 'negocios_empreendedorismo', name: 'Negócios e Empreendedorismo', requires_fee: true },
    { id: 'noticias', name: 'Notícias' },
    { id: 'outros', name: 'Outros', requires_fee: true },
    { id: 'politica', name: 'Política', requires_fee: true },
    { id: 'profissoes', name: 'Profissões' },
    { id: 'receitas', name: 'Receitas', requires_fee: true },
    { id: 'redes_sociais', name: 'Redes Sociais' },
    { id: 'religiao', name: 'Religião' },
    { id: 'shitpost', name: 'Shitpost' },
    { id: 'tecnologia', name: 'Tecnologia' }
];